### ISSUE TITLE
Trying to build telegraf in nspawn chroot fails due to depedency's requirement of IPC_LOCK capability

### ISSUE THREAD

**Issue by nogweii** [aurutils/aurutils#1044]
This took me down a deep rabbit hole, but it's as the title says. Trying to compile the [telegraf](https://aur.archlinux.org/packages/telegraf) fails when running inside a container. (Or any other highly restricted environment, like a BSD jail.) That's because the capability to lock regions of the memory is denied, and one of telegraf's dependencies, `memguard`, requires it during the compilation phase.

For aurutils, the solution is to pass `--capability=CAP_IPC_LOCK` to `systemd-nspawn`. I don't see a way to pass arguments all the way down to it though, when starting from `aur sync`. `--margs` gets passed to to `makepkg` so that's a no-go.

Technical details about the dependency are here: https://github.com/awnumar/memguard/issues/144

**Comment by AladW** [comment]
makechrootpkg does not support passing additional arguments to systemd-nspawn. So this is another one for #909.

**Comment by AladW** [comment]
Listed this issue in #909, closing for now.

**Comment by FlashSystems** [comment]
I'd like to document a workaround for anyone that stumbles upon this bug report. As noted in a [previous comment](https://github.com/AladW/aurutils/issues/1044#issuecomment-1382081729), it is not possible to pass additional arguments to systemd-nspawn. What is possible though is using a `.nspawn`-file to set the capability:

The name of the file has to be the name of the working copy used by `makechrootpkg`. The file has to be placed in `/etc/systemd/nspawn/` and the file extension must be `.nspawn`.
For example, if the directory of your working container is `/aur/buildcopy` the configuration has to go into `/etc/systemd/nspawn/buildcopy.nspawn`.

For setting the IPC_LOCK capability on the container, put the following into the nspawn-file:
```ini
[Exec]
Capability=CAP_IPC_LOCK
```

**Comment by AladW** [comment]
Nice, this is something that could be documented in `aur-chroot(1)` as well.

**Comment by Toolybird** [comment]
BTW, the `.nspawn` file tweak no longer works after a recent devtools update. Please refer [here](https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/172#note_130180) for details.

I have submitted an [MR](https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/201) to hopefully make things a bit more flexible on the devtools side.

**Comment by AladW** [comment]
Waiting for Godot as is usual with devtools... closing again. Custom `nspawn` args is something that's planned for the standalone version of `aur-chroot`.
