### ISSUE TITLE
`build`: --chroot --pkgver does not respect SRCDEST and BUILDDIR from makepkg.conf

### ISSUE THREAD

**Issue by lahwaacz** [aurutils/aurutils#1102]
When both `--chroot` and `--pkgver` are passed to `aur-build`, the `run_pkgver` logic runs the following command:

    makepkg -od --config /var/lib/aurbuild/x86_64/root/etc/makepkg.conf

This happens _outside_ the chroot and disregards the user's `makepkg.conf` where variables like `SRCDEST` and `BUILDDIR` might be set. Hence, sources are downloaded directly next to the PKGBUILD and the `src` directory is created there instead of in `BUILDDIR`, which is not what I want.

Without `--chroot`, the same logic runs just `makepkg -od` which behaves as expected. Why does `aur-build` use `/var/lib/aurbuild/x86_64/root/etc/makepkg.conf` when the command is not run inside the chroot?

**Comment by lahwaacz** [comment]
If I pass `--makepkg-conf ~/.config/pacman/makepkg.conf`, it gets copied to `/var/lib/aurbuild/x86_64/root/etc/makepkg.conf` and I get warnings due to undefined variables:

```
==> ERROR: $SRCEXT does not contain a valid package suffix (needs '.src.tar*', got '')
==> ERROR: $PKGEXT does not contain a valid package suffix (needs '.pkg.tar*', got '')
```

My `~/.config/pacman/makepkg.conf` is not a "complete" config. Without chroot, makepkg would "merge" it with `/etc/makepkg.conf`, but that does not work with `--chroot`... I could just update the config, but it is not ideal.

Performing all tasks inside the container would help with getting the `BUILDDIR` out of the PKGBUILD directory, but how would caching sources in `SRCDEST` work in that case? Also the updated PKGBUILD would have to be copied outside the chroot somehow...

**Comment by AladW** [comment]
> I could just update the config, but it is not ideal.

Another option is to create /etc/aurutils/makepkg-x86_64.conf based on /etc/makepkg.conf and changes wanted for the container.

>  how would caching sources in SRCDEST work in that case? Also the updated PKGBUILD would have to be copied outside the chroot somehow...

`systemd-nspawn --setenv` and `--bind` should cover this, see https://github.com/AladW/aurutils/blob/chroot-standalone/lib/aur-chroot#L189-L195

**Comment by aereaux** [comment]
Another workaround I've been using is to pass `SRCDEST` explicitly.  This avoids having to make modifications to any extra makepkg files, but I'm not sure what's the best way to work around this issue.

**Comment by AladW** [comment]
Listed in #909
