### ISSUE TITLE
`depends`: Missing dependency with `-a` vs `-n`.

### ISSUE THREAD

**Issue by patlefort** [aurutils/aurutils#1122]
Example: `aur depends --reverse --table -n pamac-all` has 
```
libpamac        libpamac        libpamac        11.5.7-1        Self
libpamac        pamac-cli       libpamac        11.5.7-1        Depends
```

But `aur depends --reverse --table -a pamac-all` does not.

One thing to note is that `pamac-all` depends on `pamac-cli` which depends on `libpamac` but `pamac-all` depends on `libpamac-full` which provides `libpamac`.

[aur-depends-a.log](https://github.com/AladW/aurutils/files/13196189/aur-depends-a.log)
[aur-depends-n.log](https://github.com/AladW/aurutils/files/13196190/aur-depends-n.log)

**Comment by AladW** [comment]
With the new dependency code (#1128), the output contains for both `aur depends --reverse --table -n pamac-all` and `aur depends --reverse --table -a pamac-all`
```
libpamac-full	libpamac-full	libpamac-full	1:11.6.3-1	Self
libpamac-full	pamac-cli	libpamac-full	1:11.6.3-1	Depends
libpamac-full	pamac-all	libpamac-full	1:11.6.3-1	Depends
```
The build order is also correct and no longer includes `libpamac` (11 trials):
```
% aur depends pamac-all -r | tsort
snapd
snapd-glib
libpamac-full
pamac-cli
pamac-all
```
