### ISSUE TITLE
`aur-repo`: Wrong json output with `-s --json`.

### ISSUE THREAD

**Issue by patlefort** [aurutils/aurutils#1126]
Example: `aur repo -d global -s '^oh-my-zsh-git$' -J -S`: [output.log](https://github.com/aurutils/aurutils/files/13675438/output.log)

Output is starting with a `,`. If no packages are found, it prints `]`.

**Comment by AladW** [comment]
Sorry for the delay. Should be fixed by https://github.com/aurutils/aurutils/commit/b57d06ea22b2a81414e5237104df1f95c6318f0a.
