### ISSUE TITLE
Build options per package

### ISSUE THREAD

**Issue by CatPlanet** [aurutils/aurutils#1127]
Hi, I wonder if there is option to configure single package so it could be build with different cmake arguments from now on.
More specific example: building and updating `mumble-git` without plugins (new `-Dplugins=OFF` parameter)

**Comment by AladW** [comment]
Edit the PKGBUILD and commit the change with `git commit`. Then let `aur fetch --sync=auto` or `aur sync` know it should rebase your commit, by setting `git config aurutils.rebase true`.

**Comment by CatPlanet** [comment]
Nice, thank you!

**Comment by CatPlanet** [comment]
Nice, thank you!
