### ISSUE TITLE
`sync`: system `pacman.conf` is still used with `--chroot`

### ISSUE THREAD

**Issue by abouvier** [aurutils/aurutils#1135]
Trying to build a package for a custom repo not present in the system `/etc/pacman.conf`:
```
$ aur sync --database=myrepo cantata
repo: repository myrepo not configured
```
Which is normal.
But the same error appears when building in a systemd-nspawn container whereas `myrepo` is properly configured in `/etc/aurutils/pacman-myrepo.conf`:
```
$ aur sync --chroot --database=myrepo cantata
repo: repository myrepo not configured
```
If `myrepo` is also configured in `/etc/pacman.conf` it will work and `aurutils` will still use `/etc/aurutils/pacman-myrepo.conf`.
So it seems that `sync` is still trying to check something for the repo in `/etc/pacman.conf` before rightfully using `/etc/aurutils/pacman-myrepo.conf` for the actual build.

**Comment by AladW** [comment]
Please test #1137

**Comment by abouvier** [comment]
> Please test #1137

I get this:
```
$ aur sync --chroot --database=myrepo cantata
Error:
    aur-chroot could not find a pacman.conf(5) file for container usage. Before
    using aur-chroot, make sure this file is created and valid. See OPTIONS in
    aur-chroot(1) for configuration details.
    
    The following file paths were checked:
        '/etc/aurutils/pacman-x86_64.conf'
        '/usr/share/devtools/pacman.conf.d/aurutils-x86_64.conf'
```
It seems that `/etc/aurutils/pacman-myrepo.conf` is not even checked, because `--suffix myrepo` is not sent to `aur-chroot` (only `aur-build` send this to `aur-chroot` apparently).
