### ISSUE TITLE
`sync` attempt to build dependencies satisfied by the official repositories; example: `devtools-git` -> `bzr` (satisfied by `breezy`)

### ISSUE THREAD

**Issue by 6XGate** [aurutils/aurutils#1136]
__Before filing a bug, check the following:__

1) Do you use the latest release of aurutils and its dependencies? If so,
is the issue reproducible from the master branch?
2) Does the package conform to 
[`PKGBUILD(5)`](https://www.archlinux.org/pacman/PKGBUILD.5.html) and the 
[AUR package guidelines](https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages)?
3) Does the package provide the correct metadata on the 
[AUR RPC interface](https://aur.archlinux.org/rpc.php)?
4) Does the package build with `makepkg -s` or `extra-x86_64-build` ?
5) Does the package use internal `makepkg` functions? (see [FS#43502](https://bugs.archlinux.org/task/43502))
6) Is the problem reproducible, and not due to a misconfiguration of
`pacman`, `makepkg`, `sudoers`, `gpg` or others?

__If yes to all, create a debug log:__

```
AUR_DEBUG=1 aur <name> <arguments> >aurutils.log 2>&1
```

and attach aurutils.log to this issue.

[aurutils.log](https://github.com/aurutils/aurutils/files/14234141/aurutils.log)

**Comment by AladW** [comment]
```
+(/usr/lib/aurutils/aur-repo-filter:134): printf 'dependency %s satisfied by %s/%s\n' bzr extra breezy
dependency bzr satisfied by extra/breezy
```

**Comment by 6XGate** [comment]
It sees the dependency is satisfied but still attempts to built bzr, which seems to be deprecated by Arch in favor of breezy due to the Python2 dependency of bzr.

**Comment by AladW** [comment]
It is shown in the colored version message, but not actually added to the build queue. You can verify it in vifm. Tried on `master`

**Comment by 6XGate** [comment]
I'll try running it through the full call without interruption. It was tried with master branch (checking out this repo's PKGBUILD). It keeps queuing and starting the `python2` and `brz` build for me locally.

**Comment by 6XGate** [comment]
That is the issue. **bzr** should be needed, or built, since **breezy** is present. It seems it is trying to install **brz**, and build **python2** as a dependency.

**Comment by AladW** [comment]
Superseded by #1144

**Comment by AladW** [comment]
https://github.com/aurutils/aurutils/pull/1147
