### ISSUE TITLE
Is it possible to override makepkg.conf build options in chroot when using aurutils?

### ISSUE THREAD

**Issue by Hydranet** [aurutils/aurutils#1143]
I'm using the latest version of aurutils.  Now I have come across something that  I'm not sure if is a user error or bug since I can't find in the man pages how to change the behavior. I use "aur sync -c -u" to update my AUR built packages and "aur sync -c package" to install a new AUR package. I have noticed that when I do that  that a debug package also gets built, however I manually build the PKGBUILD with "makepkg" that doesn't happen because of the following line in /etc/makepkg.conf

`OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)`

When I check the clean chroot's configuration files in the clean chroots for my user and root under /var/lib/aurbuild/x86_64/* I see that that same line is still default so that it looks like this.

```
ls /var/lib/aurbuild/x86_64/*/etc/makepkg.conf
/var/lib/aurbuild/x86_64/myuser/etc/makepkg.conf  /var/lib/aurbuild/x86_64/root/etc/makepkg.conf
```

`OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge debug lto)`

So that explains why when using aurutils to build a PKGBUILD or a new version of a PKGBUILD a debug package  also gets built. Is there a way to override this behavior, so that you can give an option or flag so that the makepkg.conf file in the chroot also has !debug option set or did I miss something in the aurutils man pages?

**Comment by AladW** [comment]
Use any of the paths defined below:
```
/etc/aurutils/makepkg-x86_64.conf
/etc/aurutils/makepkg-custom.conf   # Replace custom with your repository name
/usr/share/devtools/makepkg.conf.d/custom.conf
/usr/share/devtools/makepkg.conf.d/x86_64.conf
```
The last file is owned by the devtools package, so it would be overwritten on upgrades. Use any of the three other paths for modifications.

**Comment by Hydranet** [comment]
Thanks for the information @AladW! Is that documented anywhere, otherwise I will bookmark this issue for later reference for myself.
