### ISSUE TITLE
aur-build error (aurutils 19.2)

### ISSUE THREAD

**Issue by mlmatlock** [aurutils/aurutils#1152]
aur-build (aurutils 19.2). Command exits with a SIGPIPE:

```
aur build -d custom -c -f -S --root $repo --makepkg-conf=$HOME/.config/pacman/makepkg.conf -D $CHROOT -N --margs n,s,r,clean
```
No issue with 19.1; been using this command for a good while now.

[debug.log](https://github.com/aurutils/aurutils/files/14808931/debug.log)

**Comment by AlexKurisu** [comment]
Same error with `aur build -Csrc`

**Comment by AladW** [comment]
I've reverted https://github.com/aurutils/aurutils/commit/6f9181710f616699ef2b6f2a2ba7ac571ea393c9

Thanks for the report
