### ISSUE TITLE
`repo`: Output `]` when nothing is found with -J and -s.

### ISSUE THREAD

**Issue by patlefort** [aurutils/aurutils#1153]
Example command: `aur repo -d local-repo -s 'aaaaa' -J`.

Output:
```
]
```
[aurutils.log](https://github.com/aurutils/aurutils/files/15049213/aurutils.log)

**Comment by Earnestly** [comment]
https://github.com/aurutils/aurutils/blob/master/lib/aur-repo-parse#L46-L60

If `$pkg` isn't defined then perhaps this should print `[` in an else branch so the result becomes `[]\n`

**Comment by AladW** [comment]
Thanks for finding another issue with `--json`. Fixed with https://github.com/aurutils/aurutils/commit/232d1ce3cae0cfae91bcd11b289ec378f6d41fc0
