### ISSUE TITLE
aurutils fails when looking for orderfile in wrong place /temp${HOME}/.config/aurutils/sync/orderfile

### ISSUE THREAD

**Issue by WildPenquin** [aurutils/aurutils#1167]
Hi,

Running `aurutils sync -u` fails because aurutils is looking for orderfile in the wrong place.

I can reproduce this with aurutils and aurutils-git from the aur.

Seems like my home directory name is prepended by `/temp` for some reason (without `/` after `/temp`).

```
AUR_DEBUG=1 aur <name> <arguments> >aurutils.log 2>&1
[aurutils.log](https://github.com/user-attachments/files/15860048/aurutils.log)
```

**Comment by Earnestly** [comment]
This error is coming from `git`. Do you use any wrappers that change the behaviour of `git`? (E.g. `type -P git` in a bash shell)

**Comment by WildPenquin** [comment]
No, I did not use any wrappers.

It seems that the error was caused by the PKGBUILD of alpine. I removed the cache of alpine, and I can not reproduce anymore.

**Comment by AladW** [comment]
I guess `/temphome` was set by `git config` for some reason. `aur-sync` would only do it based on the value of `$HOME`, when a package is cloned for the first time. So `HOME=/temphome/... aur sync alpine` would break future calls of `aur sync alpine`.

**Comment by WildPenquin** [comment]
I was hit by this bug again.

Removing `.cache/aur/sync` works around the issue. This time I kept the old sync dir so I can try to reproduce this again.

Note: I do not call aur in any weird way or with any environmant variables. I got the bug by running `aur repo -u` and then `aur sync -u`.
