### ISSUE TITLE
Man page out of date (repo-add)

### ISSUE THREAD

**Issue by JaakkoHintsala** [aurutils/aurutils#1176]
The "CREATING A LOCAL REPOSITORY"-section is out of date.

The `repo-add -n custom.db.tar.gz *.pkg.tar*`-command produces the following error: `No changes made to package database.`

I was able get it to work following this comment's advice: https://gist.github.com/geosharma/afe1ea9ebe58cb67aaaba62a0d47bc7a?permalink_comment_id=5044924#gistcomment-5044924

**Comment by AladW** [comment]
[Upgrade `pacman` to `7.0.0`](https://github.com/aurutils/aurutils/issues/1168#issuecomment-2245629492)

**Comment by JaakkoHintsala** [comment]
Ah I see, thanks
