### ISSUE TITLE
[Bug]: XDG_CONFIG_HOME used but not set in aur-view

### ISSUE THREAD

**Issue by dhouck** [aurutils/aurutils#1177]
Commit d6b5a3a moved these lines from `aur-sync` to `aur-view`:
```bash
# Default to showing PKGBUILD first in patch. (#399)
orderfile=$XDG_CONFIG_HOME/aurutils/$argv0/orderfile
mkdir -p -- "${orderfile%/*}"

if [[ ! -s $orderfile ]]; then
    printf 'PKGBUILD\n' > "$orderfile"
fi
```

However, `aur-view` unlike `aur-sync` does not define `$XDG_CONFIG_HOME` at the top and relies on it being otherwise set, which it is not.  It should add the line
```bash
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
```
near the existing line to set `XDG_DATA_HOME`.  Without that line, instead of defaulting to `$HOME/.config`, it effectively defaults to `/`.  Since I am not running as root I do not have permission to create the directory `/aurutils` and I would not want to if I did.

Alternately, `aur` could export these variables so everything it calls has them available without having to duplicate these lines.

---

__Before filing a bug, check the following:__

1) Do you use the latest release of aurutils and its dependencies? If so,
is the issue reproducible from the master branch?

I am using `aur version 19.9-9-gc27bfa89`, which appears to be the master branch.

2) Does the package conform to 
[`PKGBUILD(5)`](https://www.archlinux.org/pacman/PKGBUILD.5.html) and the 
[AUR package guidelines](https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages)?
3) Does the package provide the correct metadata on the 
[AUR RPC interface](https://aur.archlinux.org/rpc.php)?
4) Does the package build with `makepkg -s` or `extra-x86_64-build` ?
5) Does the package use internal `makepkg` functions? (see [FS#43502](https://bugs.archlinux.org/task/43502))

N/A

6) Is the problem reproducible, and not due to a misconfiguration of
`pacman`, `makepkg`, `sudoers`, `gpg` or others?

Yes

__If yes to all, create a debug log:__
```
AUR_DEBUG=1 aur <name> <arguments> >aurutils.log 2>&1
```
and attach aurutils.log to this issue.

The relevant section of the debug log is; I would prefer not to attach the full thing.
```
+(/usr/lib/aurutils/aur-view:85): mkdir -p -- /home/dhouck/.local/share/aurutils/view
+(/usr/lib/aurutils/aur-view:88): orderfile=/aurutils/view/orderfile
+(/usr/lib/aurutils/aur-view:89): mkdir -p -- /aurutils/view
mkdir: cannot create directory ‘/aurutils’: Permission denied
+(/usr/lib/aurutils/aur-view:1): trap_exit
+(/usr/lib/aurutils/aur-view:20): trap_exit(): [[ ! -v AUR_DEBUG ]]
+(/usr/lib/aurutils/aur-view:23): trap_exit(): printf 'AUR_DEBUG: %s: temporary files at %s\n' view /tmp/aurutils-1000/view.8lpIR7G
AUR_DEBUG: view: temporary files at /tmp/aurutils-1000/view.8lpIR7G
+(/usr/lib/aurutils/aur-sync:1): trap_exit
+(/usr/lib/aurutils/aur-sync:63): trap_exit(): [[ ! -v AUR_DEBUG ]]
+(/usr/lib/aurutils/aur-sync:66): trap_exit(): printf 'AUR_DEBUG: %s: temporary files at %s\n' sync /tmp/aurutils-1000/sync.z1baOPyd
AUR_DEBUG: sync: temporary files at /tmp/aurutils-1000/sync.z1baOPyd
```

**Comment by AladW** [comment]
I added the missing `XDG_CONFIG_HOME` in #1178. I think this is a better approach than exporting the variables in `aur`, since that implies `aur-view` could no longer be run direcly.
