### ISSUE TITLE
aur sync/aur deps reports check dependencies for parent packages

### ISSUE THREAD

**Issue by BrainDamage** [aurutils/aurutils#1184]
aur sync, tries to compile/fetch check dependencies for parent packages, instead of only the currently active one

case in point:  [python-diffusers](https://aur.archlinux.org/packages/python-diffusers) package, it doesn't have any check dependency listed, but aur sync python-diffusers will attempt to compile python-jax/python-jaxlib and several other packages. Passing --nocheck to aur sync makes them be skipped

I think it's a consequence of how aur depends is managed:
 
`aur depends --table python-diffusers`
> python-optax	python-jax
> python-flax	python-jax
> python-chex	python-jax
> **python-safetensors	python-jax**
> python-orbax-checkpoint	python-jax
> python-safetensors	python-huggingface-hub
> python-diffusers	python-huggingface-hub
> python-diffusers	python-diffusers
> **python-safetensors	python-flax**
> python-flax	python-orbax-checkpoint
> python-chex	python-dm-tree
> python-orbax-checkpoint	python-tensorstore
> python-flax	python-tensorstore
> python-flax	python-optax
> python-optax	python-chex
> python-jax	python-jaxlib
> **python-safetensors	python-jaxlib**
> python-diffusers	python-safetensors
> python-orbax-checkpoint	python-etils

but if we check [python-safetensors](https://aur.archlinux.org/packages/python-safetensors?all_deps=1#pkgdeps) those packages are only listed as checkdepends / optional.
I am positive it only includes checkdepends because eg python-paddlepaddle is not listed as a candidate dependency

if we try `aur depends --table python-diffusers`, we'll notice several "CheckDepends" packages, but those are checkdepends for parent packages and are not necessary to execute the check function of the current one, yet are used by aur sync as if they were

> python-dm-tree	python-dm-tree	python-dm-tree	0.1.8-1	Self
> python-dm-tree	python	python-dm-tree	0.1.8-1	Depends
> python-dm-tree	python-six	python-dm-tree	0.1.8-1	Depends
> python-dm-tree	abseil-cpp	python-dm-tree	0.1.8-1	Depends
> python-dm-tree	python	python-dm-tree	0.1.8-1	MakeDepends
> python-dm-tree	python-build	python-dm-tree	0.1.8-1	MakeDepends
> python-dm-tree	python-installer	python-dm-tree	0.1.8-1	MakeDepends
> python-dm-tree	python-wheel	python-dm-tree	0.1.8-1	MakeDepends
> python-dm-tree	python-setuptools	python-dm-tree	0.1.8-1	MakeDepends
> python-dm-tree	cmake	python-dm-tree	0.1.8-1	MakeDepends
> python-dm-tree	git	python-dm-tree	0.1.8-1	MakeDepends
> python-etils	python-etils	python-etils	1.9.4-1	Self
> python-etils	python	python-etils	1.9.4-1	Depends
> python-etils	python-build	python-etils	1.9.4-1	MakeDepends
> python-etils	python-installer	python-etils	1.9.4-1	MakeDepends
> python-etils	python-flit-core	python-etils	1.9.4-1	MakeDepends
> python-etils	python-wheel	python-etils	1.9.4-1	MakeDepends
> python-optax	python-optax	python-optax	0.2.3-1	Self
> python-optax	python-absl	python-optax	0.2.3-1	Depends
> python-optax	python-chex	python-optax	0.2.3-1	Depends
> python-optax	python-jax	python-optax	0.2.3-1	Depends
> python-optax	python-numpy	python-optax	0.2.3-1	Depends
> python-optax	python-build	python-optax	0.2.3-1	MakeDepends
> python-optax	python-installer	python-optax	0.2.3-1	MakeDepends
> python-optax	python-flit-core	python-optax	0.2.3-1	MakeDepends
> python-optax	python-wheel	python-optax	0.2.3-1	MakeDepends
> python-flax	python-flax	python-flax	0.9.0-1	Self
> python-flax	python-jax	python-flax	0.9.0-1	Depends
> python-flax	python-msgpack	python-flax	0.9.0-1	Depends
> python-flax	python-numpy	python-flax	0.9.0-1	Depends
> python-flax	python-optax	python-flax	0.9.0-1	Depends
> python-flax	python-orbax-checkpoint	python-flax	0.9.0-1	Depends
> python-flax	python-rich	python-flax	0.9.0-1	Depends
> python-flax	python-tensorstore	python-flax	0.9.0-1	Depends
> python-flax	python-typing_extensions	python-flax	0.9.0-1	Depends
> python-flax	python-yaml	python-flax	0.9.0-1	Depends
> python-flax	python-build	python-flax	0.9.0-1	MakeDepends
> python-flax	python-installer	python-flax	0.9.0-1	MakeDepends
> python-flax	python-setuptools	python-flax	0.9.0-1	MakeDepends
> python-flax	python-setuptools-scm	python-flax	0.9.0-1	MakeDepends
> python-flax	python-wheel	python-flax	0.9.0-1	MakeDepends
> python-huggingface-hub	python-huggingface-hub	python-huggingface-hub	1:0.25.1-1	Self
> python-huggingface-hub	python-aiohttp	python-huggingface-hub	1:0.25.1-1	Depends
> python-huggingface-hub	python-fastapi	python-huggingface-hub	1:0.25.1-1	Depends
> python-huggingface-hub	python-fsspec	python-huggingface-hub	1:0.25.1-1	Depends
> python-huggingface-hub	python-filelock	python-huggingface-hub	1:0.25.1-1	Depends
> python-huggingface-hub	python-numpy	python-huggingface-hub	1:0.25.1-1	Depends
> python-huggingface-hub	python-packaging	python-huggingface-hub	1:0.25.1-1	Depends
> python-huggingface-hub	python-pydantic	python-huggingface-hub	1:0.25.1-1	Depends
> python-huggingface-hub	python-requests	python-huggingface-hub	1:0.25.1-1	Depends
> python-huggingface-hub	python-tqdm	python-huggingface-hub	1:0.25.1-1	Depends
> python-huggingface-hub	python-yaml	python-huggingface-hub	1:0.25.1-1	Depends
> python-huggingface-hub	python-build	python-huggingface-hub	1:0.25.1-1	MakeDepends
> python-huggingface-hub	python-installer	python-huggingface-hub	1:0.25.1-1	MakeDepends
> python-huggingface-hub	python-setuptools	python-huggingface-hub	1:0.25.1-1	MakeDepends
> python-huggingface-hub	python-wheel	python-huggingface-hub	1:0.25.1-1	MakeDepends
> python-safetensors	python-safetensors	python-safetensors	0.4.5-1	Self
> python-safetensors	python	python-safetensors	0.4.5-1	Depends
> python-safetensors	python-build	python-safetensors	0.4.5-1	MakeDepends
> python-safetensors	python-installer	python-safetensors	0.4.5-1	MakeDepends
> python-safetensors	python-maturin	python-safetensors	0.4.5-1	MakeDepends
> python-safetensors	python-wheel	python-safetensors	0.4.5-1	MakeDepends
> python-safetensors	python-setuptools-rust	python-safetensors	0.4.5-1	MakeDepends
> **python-safetensors	python-pytorch	python-safetensors	0.4.5-1	CheckDepends
> python-safetensors	python-numpy	python-safetensors	0.4.5-1	CheckDepends
> python-safetensors	python-tensorflow	python-safetensors	0.4.5-1	CheckDepends
> python-safetensors	python-jax	python-safetensors	0.4.5-1	CheckDepends
> python-safetensors	python-flax	python-safetensors	0.4.5-1	CheckDepends
> python-safetensors	python-jaxlib	python-safetensors	0.4.5-1	CheckDepends
> python-safetensors	python-black	python-safetensors	0.4.5-1	CheckDepends
> python-safetensors	python-isort	python-safetensors	0.4.5-1	CheckDepends
> python-safetensors	flake8	python-safetensors	0.4.5-1	CheckDepends
> python-safetensors	python-click	python-safetensors	0.4.5-1	CheckDepends
> python-safetensors	python-huggingface-hub	python-safetensors	0.4.5-1	CheckDepends
> python-safetensors	python-pytest	python-safetensors	0.4.5-1	CheckDepends
> python-safetensors	python-pytest-benchmark	python-safetensors	0.4.5-1	CheckDepends
> python-safetensors	python-h5py	python-safetensors	0.4.5-1	CheckDepends**
> python-chex	python-chex	python-chex	0.1.86-2	Self
> python-chex	python-absl	python-chex	0.1.86-2	Depends
> python-chex	python-jax>=0.4.16	python-chex	0.1.86-2	Depends
> python-chex	python-numpy	python-chex	0.1.86-2	Depends
> python-chex	python-toolz	python-chex	0.1.86-2	Depends
> python-chex	python-typing_extensions	python-chex	0.1.86-2	Depends
> python-chex	python-build	python-chex	0.1.86-2	MakeDepends
> python-chex	python-installer	python-chex	0.1.86-2	MakeDepends
> python-chex	python-setuptools	python-chex	0.1.86-2	MakeDepends
> python-chex	python-wheel	python-chex	0.1.86-2	MakeDepends
> python-chex	python-cloudpickle	python-chex	0.1.86-2	CheckDepends
> python-chex	python-dm-tree	python-chex	0.1.86-2	CheckDepends
> python-chex	python-pytest	python-chex	0.1.86-2	CheckDepends
> python-diffusers	python-diffusers	python-diffusers	0.30.3-1	Self
> python-diffusers	python-filelock	python-diffusers	0.30.3-1	Depends
> python-diffusers	python-huggingface-hub	python-diffusers	0.30.3-1	Depends
> python-diffusers	python-numpy	python-diffusers	0.30.3-1	Depends
> python-diffusers	python-pillow	python-diffusers	0.30.3-1	Depends
> python-diffusers	python-regex	python-diffusers	0.30.3-1	Depends
> python-diffusers	python-requests	python-diffusers	0.30.3-1	Depends
> python-diffusers	python-safetensors	python-diffusers	0.30.3-1	Depends
> python-diffusers	python-build	python-diffusers	0.30.3-1	MakeDepends
> python-diffusers	python-installer	python-diffusers	0.30.3-1	MakeDepends
> python-diffusers	python-setuptools	python-diffusers	0.30.3-1	MakeDepends
> python-diffusers	python-wheel	python-diffusers	0.30.3-1	MakeDepends
> python-jax	python-jax	python-jax	0.4.33-1	Self
> python-jax	python-absl	python-jax	0.4.33-1	Depends
> python-jax	python-jaxlib>=0.4.33	python-jax	0.4.33-1	Depends
> python-jax	python-ml-dtypes	python-jax	0.4.33-1	Depends
> python-jax	python-numpy	python-jax	0.4.33-1	Depends
> python-jax	python-opt_einsum	python-jax	0.4.33-1	Depends
> python-jax	python-scipy	python-jax	0.4.33-1	Depends
> python-jax	python-build	python-jax	0.4.33-1	MakeDepends
> python-jax	python-installer	python-jax	0.4.33-1	MakeDepends
> python-jax	python-setuptools	python-jax	0.4.33-1	MakeDepends
> python-jax	python-wheel	python-jax	0.4.33-1	MakeDepends
> python-orbax-checkpoint	python-orbax-checkpoint	python-orbax-checkpoint	0.6.4-1	Self
> python-orbax-checkpoint	python-absl	python-orbax-checkpoint	0.6.4-1	Depends
> python-orbax-checkpoint	python-etils	python-orbax-checkpoint	0.6.4-1	Depends
> python-orbax-checkpoint	python-importlib_resources	python-orbax-checkpoint	0.6.4-1	Depends
> python-orbax-checkpoint	python-jax	python-orbax-checkpoint	0.6.4-1	Depends
> python-orbax-checkpoint	python-msgpack	python-orbax-checkpoint	0.6.4-1	Depends
> python-orbax-checkpoint	python-nest-asyncio	python-orbax-checkpoint	0.6.4-1	Depends
> python-orbax-checkpoint	python-numpy	python-orbax-checkpoint	0.6.4-1	Depends
> python-orbax-checkpoint	python-protobuf	python-orbax-checkpoint	0.6.4-1	Depends
> python-orbax-checkpoint	python-tensorstore	python-orbax-checkpoint	0.6.4-1	Depends
> python-orbax-checkpoint	python-typing_extensions	python-orbax-checkpoint	0.6.4-1	Depends
> python-orbax-checkpoint	python-yaml	python-orbax-checkpoint	0.6.4-1	Depends
> python-orbax-checkpoint	python-build	python-orbax-checkpoint	0.6.4-1	MakeDepends
> python-orbax-checkpoint	python-flit-core	python-orbax-checkpoint	0.6.4-1	MakeDepends
> python-orbax-checkpoint	python-installer	python-orbax-checkpoint	0.6.4-1	MakeDepends
> python-tensorstore	python-tensorstore	python-tensorstore	0.1.65-1	Self
> python-tensorstore	blosc	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	brotli	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	bzip2	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	c-ares	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	curl	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	libavif	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	libjpeg-turbo	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	libnghttp2	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	libpng	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	libtiff	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	libwebp	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	lz4	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	pybind11	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	python-ml-dtypes	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	python-numpy	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	snappy	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	xz	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	zlib	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	zstd	python-tensorstore	0.1.65-1	Depends
> python-tensorstore	python-build	python-tensorstore	0.1.65-1	MakeDepends
> python-tensorstore	python-installer	python-tensorstore	0.1.65-1	MakeDepends
> python-tensorstore	python-setuptools	python-tensorstore	0.1.65-1	MakeDepends
> python-tensorstore	python-setuptools-scm	python-tensorstore	0.1.65-1	MakeDepends
> python-tensorstore	python-wheel	python-tensorstore	0.1.65-1	MakeDepends
> python-jaxlib	python-jaxlib	python-jaxlib	0.4.31-1	Self
> python-jaxlib	python-absl	python-jaxlib	0.4.31-1	Depends
> python-jaxlib	python-flatbuffers	python-jaxlib	0.4.31-1	Depends
> python-jaxlib	python-ml-dtypes>=0.4.0	python-jaxlib	0.4.31-1	Depends
> python-jaxlib	python-numpy	python-jaxlib	0.4.31-1	Depends
> python-jaxlib	python-scipy	python-jaxlib	0.4.31-1	Depends
> python-jaxlib	python-build	python-jaxlib	0.4.31-1	MakeDepends
> python-jaxlib	python-installer	python-jaxlib	0.4.31-1	MakeDepends
> python-jaxlib	python-setuptools	python-jaxlib	0.4.31-1	MakeDepends
> python-jaxlib	python-wheel	python-jaxlib	0.4.31-1	MakeDepends

those bogus checkdepends should be discarded, perhaps by aur depends itself, if not, they should at least be ignored  by aur sync

**Comment by Earnestly** [comment]
> aur sync, tries to compile/fetch check dependencies for parent packages, instead of only the currently active one

It's not clear to me if you are either suggesting that dependencies of dependent packages being built for the final package rather than for each respective dependency themselves, or if you're suggesting that `aur sync` just shouldn't build or include checkdepends or optdepends.

> case in point: [python-diffusers](https://aur.archlinux.org/packages/python-diffusers) package, it doesn't have any check dependency listed, but aur sync python-diffusers will attempt to compile python-jax/python-jaxlib and several other packages. **Passing --nocheck to aur sync makes them be skipped**

Isn't this working correctly?

> but if we check [python-safetensors](https://aur.archlinux.org/packages/python-safetensors?all_deps=1#pkgdeps) those packages are only listed as checkdepends / optional. I am positive it only includes checkdepends because eg python-paddlepaddle is not listed as a candidate dependency

As they are dependencies, what is wrong with `aur sync` doing this?

> if we try `aur depends --table python-diffusers`, we'll notice several "CheckDepends" packages, but those are checkdepends for parent packages and are not necessary to execute the check function of the current one, yet are used by aur sync as if they were
> th[e]se bogus checkdepends should be discarded, perhaps by aur depends itself, if not, they should at least be ignored by aur sync

The `checkepends` listed appear to be for their respective package (not parent?), e.g. `python-safetensors` does actually depend on `python-jax` and `python-jaxlib` according to its [`PKGBUILD`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-safetensors#n26).

This is why I'm a little unsure what parent package means in this context.

**Comment by BrainDamage** [comment]
I think I have figured out the confusion, I forgot to mention that *all* the parent packages were already built, only python-diffusers needed to be built/updated, making aur sync operation equivalent to a plain makepkg -s

> if you're suggesting that aur sync just shouldn't build or include checkdepends or optdepends.
aur sync does not include optdepends any case, for neither the active package(s) being built nor any other
the problem here is that checkdepends are attempted to be built and/or installed even for a package that's available in my personal repository, as if the package was attempted to be built, while it's not

> Isn't this working correctly?
it's a workaround for the symptom of the problem

> As they are dependencies, what is wrong with aur sync doing this?
the packages aren't being built so it's wrong to install them, same way you don't install makedepends when you just depend on a built package

**Comment by AladW** [comment]
Seems it's the same old issue of dependencies not being removed recursively from the graph:
```
% aur sync--filter -p depends.jsonl
python-optax	python-flax
python-flax	python-safetensors
python-safetensors	python-diffusers
python-jaxlib	python-jax
python-jaxlib	python-safetensors
python-diffusers	python-diffusers
python-etils	python-orbax-checkpoint
python-chex	python-optax
python-dm-tree	python-chex
python-tensorstore	python-flax
python-tensorstore	python-orbax-checkpoint
python-huggingface-hub	python-diffusers
python-huggingface-hub	python-safetensors
python-jax	python-orbax-checkpoint
python-jax	python-chex
python-jax	python-flax
python-jax	python-safetensors
python-jax	python-optax
python-orbax-checkpoint	python-flax
```
```
% aur sync--filter -p depends.jsonl --ignore-file filter
python-dm-tree	python-chex
python-etils	python-orbax-checkpoint
python-optax	python-flax
python-jax	python-optax
python-jax	python-chex
python-jax	python-orbax-checkpoint
python-jax	python-flax
python-orbax-checkpoint	python-flax
python-diffusers	python-diffusers
python-chex	python-optax
python-tensorstore	python-orbax-checkpoint
python-tensorstore	python-flax
python-jaxlib	python-jax
```

**Comment by BrainDamage** [comment]
The bug seems resolved in the pending pull request branch

**Comment by AladW** [comment]
Before merging, I need to test it doesn't break existing cases (`test/packages`) or regress performance
