### ISSUE TITLE
`aur build` AUR repo located outside HOME issues.

### ISSUE THREAD

**Issue by Cody-Learner** [aurutils/aurutils#1188]
I found I had to wrap `aur build` in`chmod 646 /build/aur.db.tar.gz` with an AUR repo not under HOME. It seems pacman changes the owner and permissions to `root:root 644` on the `aur.db.tar.gz` each time it uses it. 

To be clear though, this is in an nspawn container and forwarding commands through `systemd-nspawn`, so this may be a contributing factor to this. I got something about, 'cannot access 'aur.db.tar.gz' error with an exit before adding the permission changes/restores.

https://github.com/Cody-Learner/aurch/blob/3c5ffaec868fa2784e78fecba2bf5eb114cc4905/aurch.sh#L145
https://github.com/Cody-Learner/aurch/blob/3c5ffaec868fa2784e78fecba2bf5eb114cc4905/aurch.sh#L242
https://github.com/Cody-Learner/aurch/blob/3c5ffaec868fa2784e78fecba2bf5eb114cc4905/aurch.sh#L257

Is this expected behavior or something else?

Note: 
On my previous edited out issue, after looking into it more, the feature request is actually not needed. My script just needs cleaned up and apply what is already available from `aur build --results=file`,  the `build:file:/// .....` entry will work.

I do have a question remaining though, what is the condition that triggers `exist:` to be printed to  
`aur build --results=file`?

I was thinking a pkg being built, residing in pacman's sync or local db's, this seems not the case though.

**Comment by AladW** [comment]
`chown` to `root` is something `pacman` does for packages, if `DownloadUser` is enabled, but I'm not aware it does so for the repository files as well.

The condition for `exist` as of 20.4 is that at least part of a package group is built. Currently this can result in both `build:` and `exist:` entries for the same package (if say, the `foo-debug` package is present but `foo` is not). Arguably, `exist:` entries should only arise when the full package group is available, with an error otherwise:
```diff
diff --git a/lib/pacman/aur-build b/lib/pacman/aur-build
index 72f56734..50dacd83 100755
--- a/lib/pacman/aur-build
+++ b/lib/pacman/aur-build
@@ -387,16 +387,21 @@ while IFS= read "${read_args[@]}" -ru "$fd" path; do
             printf '%q\n' >&2 "${exists[@]}"
             create_package=0
 
+            if [[ -v results_file ]]; then
+                printf "exist:file://%s\n" "${exists[@]}" | tee -a "$results_file" >/dev/null
+            fi
+
         elif (( ${#exists[@]} )); then
             # Since `makepkg` does not allow building split packages
             # individually, we restart the build when part of the
             # package group is unavailable (including -debug packages)
-            printf >&2 '%s: warning: package group partially built\n' "$argv0"
+            printf >&2 '%s: error: package group partially built\n' "$argv0"
             printf '%q\n' >&2 "${exists[@]}"
-        fi
 
-        if (( ${#exists[@]} )) && [[ -v results_file ]]; then
-            printf "exist:file://%s\n" "${exists[@]}" | tee -a "$results_file" >/dev/null
+            # Rebuilding the package at this stage may result in
+            # checksum errors, if part of the package group is
+            # available in pacman's cache, so we exit with an error.
+            exit 2
         fi
     fi
```

**Comment by Cody-Learner** [comment]
> chown to root is something pacman does for packages, if DownloadUser is enabled, but I'm not aware it does so for the repository files as well.

The following is with 'DownloadUser' and `sandboxing` enabled. ie: default `pacman.conf`.

IIRC, If the AUR repo directory is created under `HOME` with owner:group `USER:USER` , all contents of AUR repo dir contents including the `pacman *.db's` stay owner USER:USER. 

However, if the AUR repo directory is created outside `HOME`, regardless of what the permissions are set on the directory and contents, they get changed to ROOT:ROOT, and the directory 644.

This makes the `pacman *.db's` inaccessible by `aur build`. Not sure who the USER is of `aur build`, is nor the exact point of failed access.

With an AUR repo under `HOME`, I never had any issues before `pacman 7`, and after `pacman 7`, after making some permission changes to accommodate user `alpm` access ie: `setfacl -m g:alpm:r-x "${HOME}"`* , everything was good. 

* Several different installs and fixes.... This one may have started with 700 or 750 permission set on HOME.

Is there anything I can do to help with more precisely diagnosing this issue? 
Are there better alternatives to how I'm dealing with this issue?


Unrelated but worth a mention and let me know if start a new issue.

Working on a new script using` and `aur build` to make clean chroot packages.
 I found rapid back to back sudo calls from pacman using `aur build -cfns --results=aur-build.log`.
My temp workaround is:

`printf '%s\n' "${USER} ALL=(ALL) NOPASSWD: /usr/bin/pacman" |
				sudo tee /etc/sudoers.d/aurch &>/dev/null`
`aur build ....`
`sudo rm /etc/sudoers.d/aurch`


Any pointers towards a better solution would be great.

**Comment by AladW** [comment]
> Any pointers towards a better solution would be great.

`aur-build` has limited support for running as root: see `examples/sync-asroot`. The main challenge is replicating `makepkg -s`, since `makepkg` only supports running as a regular user with `sudo` escalation to install/remove dependencies. See #1173.
