### ISSUE TITLE
libastal-meta package pacman could not resolve dependencies

### ISSUE THREAD

**Issue by crimsonduelist** [aurutils/aurutils#1189]
This  [libastal-meta](https://aur.archlinux.org/packages/libastal-meta) package builds with yay and paru normally but with aurutils, pacman wont resolve dependencies. The [pkgbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libastal-meta) doesnt specify the "-git" versions i.e. instead of libastal-auth-git it  lists libastal-auth as a dependency which itself doesnt exist in the aur. However yay and paru do resolve them.
Now If I explicitly sync libastal-auth-git packages with aurutils into my custom repo and then pacman -S the package it will resolve it.
But is this expected behaviour or should aurutils actually resolve the to the -git versions? Cuz as makepkg -s will give out the same error I thought it was normal but yay and paru ll still resolve those?
Sorry If I m missing smthing obvious.
[aurutils.log](https://github.com/user-attachments/files/17981419/aurutils.log)

**Comment by AladW** [comment]
See https://github.com/aurutils/aurutils/issues/1042.
