### ISSUE TITLE
Depenency names for split packages

### ISSUE THREAD

**Issue by danielshub** [aurutils/aurutils#1190]
I am trying to build the psychopy package (https://aur.archlinux.org/packages/psychopy) and all of its dependencies, but only if they are out of date. The psychopy package depends on the python-pyglet package (https://aur.archlinux.org/packages/python-pyglet). The python-pyglet package is a split package of pyglet. The issue I am running into is that `aur depends -r psychopy` returns the dependency as `pyglet` and not `python-pyglet`. This means that if I naively do 

```
$ aur fetch pyglet
$ aur build ...
$ aur query -t info pyglet
    {"resultcount":0,"results":[],"type":"multiinfo","version":5}
```
it does not find the python-pyglet package and instead I need to run

```
$ aur query -t info python-pyglet
{"resultcount":1,"results":[{"Depends":["python","glu","python-future"],"Description":"A cross-platform windowing and multimedia library for Python","FirstSubmitted":1680344362,"ID":1616225,"Keywords":[],"LastModified":1735000507,"License":["BSD"],"Maintainer":"konez2k","MakeDepends":["python-setuptools"],"Name":"python-pyglet","NumVotes":0,"OptDepends":["ffmpeg","openal"],"OutOfDate":null,"PackageBase":"pyglet","PackageBaseID":192192,"Popularity":0,"Submitter":"arojas","URL":"https://github.com/pyglet/pyglet","URLPath":"/cgit/aur.git/snapshot/python-pyglet.tar.gz","Version":"2.0.20-2"}],"type":"multiinfo","version":5}
```
How do I list the actual dependency names for split packages so that I know that I need to fetch pyglet and query python-pyglet?

**Comment by Earnestly** [comment]
The pyglet [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pyglet) seems quite obnoxious.
Why does it only have a single `package()` function yet use split-packaging techniques via `pkgbase`?
The import from community repo has the same form, so perhaps it once had split documentation and such.

The dependency resolution seems correct, I'm not sure what purpose your `aur query` is used for wrt building the package though (as in, why you're appearing to build each dependency manually).

The `query` however problem may be a limitation of aurweb though, I'm not sure.

**Comment by danielshub** [comment]
> The pyglet [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pyglet) seems quite obnoxious. Why does it only have a single `package()` function yet use split-packaging techniques via `pkgbase`? The import from community repo has the same form, so perhaps it once had split documentation and such.
 
I think it used to be a "proper" split package when it was in community

> The dependency resolution seems correct, I'm not sure what purpose your `aur query` is used for wrt building the package though (as in, why you're appearing to build each dependency manually).

I build each package individually because my code predates aurutils :). I swapped in aur utils subcommands where I could easily replace my crappy code. I cannot hand off everything to aur utils yet. The subcommands is one of the things I like about aur utils compared to yay/paru/... and has made the transition bearable.

> The `query` however problem may be a limitation of aurweb though, I'm not sure.

I will take a look at aurweb to see if I can query something else.

**Comment by AladW** [comment]
`aurweb` does not support querying via `pkgbase`. To instead return `pkgname` in `aur-depends`, use `-n` / `--pkgname`.

**Comment by Earnestly** [comment]
@AladW Does it make much sense to logically assume `pkgname=$pkgbase` if `pkgname` is not an array (or has one element) and `pkgname` is equal to `pkgbase` for this purpose (`query`)?

**Comment by danielshub** [comment]
@AladW such an easy solution that is right in the manual :) Thanks for a great tool.

**Comment by AladW** [comment]
> Does it make much sense to logically assume pkgname=$pkgbase if pkgname is not an array (or has one element) and pkgname is equal to pkgbase for this purpose (query)?

According to `PKGBUILD(5)`
> pkgbase
>
> The name used to refer to the group of packages in the output of makepkg and in the naming of source-only tarballs. **If not specified, the first element in the pkgname array is used.**

so that `pkgname != pkgbase` is possible even when `pkgname` has only a single entry.
