### ISSUE TITLE
`sync`: `--provides` fails to filter out unneeded transitive (make) dependency

### ISSUE THREAD

**Issue by skystrife** [aurutils/aurutils#592]
EDIT: Using `master` branch.

With `mongodb-bin` available,

```bash
$ aur sync unifi --provides
==> Using [aur] repository
  -> mongodb: (none) -> 4.0.12-1
  -> python2-scons: (none) -> 3.1.1-1
  -> unifi: 5.10.25-1 -> 5.10.26-1
    dependency mongodb satisfied by mongodb-bin
```
still tries to install `python2-scons`, which should not be needed if `mongodb-bin` is fulfilling the `mongodb` dependency of `unifi`.

If a dependency is satisfied via `--provides`, I would expect the leaves of that dependency tree to also be pruned. In this case, it seems like only `mongodb` is being pruned, but not its (make) dependency `python2-scons`.

[aurlog.txt](https://github.com/AladW/aurutils/files/3489231/aurlog.txt)

**Comment by AladW** [comment]
Thanks for the report. As you might have expected from the very late reply, this is non-trivial to implement. https://github.com/AladW/aurutils/issues/350#issuecomment-383278892 might give some ideas.

**Comment by AladW** [comment]
Please test #790

**Comment by AladW** [comment]
With an actual dependency graph available (through `aur-sync--ninja`), this should be possible to implement.

**Comment by AladW** [comment]
This should be covered by the new dependency code (`Depends.pm`), specifically `Depends::prune` which does a kind of reference counting.
