### ISSUE TITLE
`sync`: notify user of maintainer change

### ISSUE THREAD

**Issue by Strykar** [aurutils/aurutils#737]
Is this something you'd consider adding?

**Comment by AladW** [comment]
As far as I know `bauerbill` and `aurto` have this implemented in some way. I didn't check in what way though.

**Comment by AladW** [comment]
Note you can also just subscribe to email notifications for the packages you use (I guess this only scales to a certain amount of packages).

One approach is to save the maintainer similar as the viewed commit is stored. A simple way is to add a subdirectory:
```
$XDG_DATA_HOME/aurutils/view/<package_foo>/commit
$XDG_DATA_HOME/aurutils/view/<package_foo>/maintainer
...
```
How a maintainer change would look like in the actual UI is unclear and perhaps best left to the user.

**Comment by AladW** [comment]
I don't think this can be implemented in a tool that operates on the level of the git repository (committer and AUR maintainer are not necessarily the same). So a higher level tool like `aur-sync` would run `aur-query` on the target set of packages, retrieve the maintainer, and compare it to cached version. Regarding the UI, a warning on `stdout` seems the obvious option, but when switching to a file manager people might miss those easily. So it would be displayed alongside the diffs somehow.

All this sounds rather convoluted to me. Rather than warn or show the changes in the file manager, I'd abort on an unexpected maintainer change, and have the user confirm the changes manually. And then you're really close to an existing solution like `aurto`.

If someone has more ideas about this, feel free to propose them. For now, for the reasons outlined above I'm closing this issue.

**Comment by FichteFoll** [comment]
Would it be feasible to simply add a file to the review process for a package where the maintainer changed? Or maybe even include it in the created `.diff` files as a separate virtual file?

**Comment by AladW** [comment]
> Or maybe even include it in the created .diff files as a separate virtual file?

That sounds like a reasonable idea, though I guess it could only be implemented in `aur-view` (which in turn loses some of its generality). The maintainer could be saved in `$XDG_DATA_HOME/aurutils/view/<package_foo>/maintainer` as outlined above. Then a `diff` from the current maintainer (`aur-query -t info <packages> | jq '.results[] | .Maintainer`) could be prepended to the package diff.

Conceptually I'd prefer to implement this in `aur-sync`, but then it would be unclear where to store the `maintainer` file, and it would have to manually operate on the diffs generated by `aur-view`.

**Comment by Earnestly** [comment]
Can the concept of `maintainer` files be generalised as a form of `userdata` that you might typically find in C style callback functions?

**Comment by AladW** [comment]
Yes, this could definitely work. The `userdata` could be taken from the command-line, `git diff`'ed, and saved in the `aur-view` directory. And the contents are then generated in `aur-sync`.

**Comment by AladW** [comment]
Here's a prototype using author files. I didn't look into `userdata` yet.
```diff
diff --git a/lib/aur-view b/lib/aur-view
index 28a440b3..380feffe 100755
--- a/lib/aur-view
+++ b/lib/aur-view
@@ -81,9 +81,6 @@ mkdir -pm 0700 -- "${TMPDIR:-/tmp}/aurutils-$UID"
 tmp=$(mktemp -d --tmpdir "aurutils-$UID/$argv0.XXXXXXX")
 trap 'trap_exit' EXIT
 
-# Directory for git checksums (revisions viewed by the user, #379)
-mkdir -p -- "$AUR_VIEW_DB"
-
 # Take input from a file instead of redirecting stdin (#871)
 packages=()
 if [[ -v queue ]]; then
@@ -108,14 +105,20 @@ for pkg in "${packages[@]}"; do
 done | xargs -0 ln -t "$tmp" -s --
 
 # Retrieve last viewed revisions
-declare -A heads
+declare -A heads heads_author
 
 for pkg in "${packages[@]}"; do
     git() { command git -C "$pkg" "$@"; }
 
+    # Directory for git checksums (revisions viewed by the user, #379)
+    mkdir -p -- "$AUR_VIEW_DB/$pkg"
+
     # Ensure every directory is a git repository (--continue)
     if head=$(git rev-parse "${revision:-HEAD}"); then
+        # Store last revision
         heads[$pkg]=$head
+        # Store commiter name and author (#737)
+        heads_author[$pkg]=$(git log --format='%an <%ae>' "$head^!")
     else
         printf >&2 '%s: %s: revision %s not found\n' "$argv0" "$pkg" "${revision:-HEAD}"
         exit 2
@@ -126,7 +129,7 @@ for pkg in "${packages[@]}"; do
         path_args=(--src-prefix="$pkg/" --dst-prefix="$pkg/")
     fi
 
-    if [[ -f $AUR_VIEW_DB/$pkg ]] && read -r view < "$AUR_VIEW_DB/$pkg"; then
+    if [[ -f $AUR_VIEW_DB/$pkg/head ]] && read -r view < "$AUR_VIEW_DB/$pkg/head"; then
         # Check if hash points to an existing object
         if ! git cat-file -e "$view"; then
             printf >&2 '%s: %s: invalid git revision\n' "$argv0" "$AUR_VIEW_DB/$pkg"
@@ -134,11 +137,26 @@ for pkg in "${packages[@]}"; do
         fi
 
         if [[ $view != "$head" ]]; then
+            # Print package diff
             git --no-pager "$log_fmt" --stat "${log_args[@]}" "${path_args[@]}" \
-                "$view..$head" -- "${excludes[@]}" > "$tmp/$pkg.$log_fmt"
+                "$view..$head" -- "${excludes[@]}" >"$tmp/$pkg.$log_fmt"
+
+            # Print author diff on changed revision (to separate file)
+            if [[ -f $AUR_VIEW_DB/$pkg/author ]] && read -r view_author < "$AUR_VIEW_DB/$pkg/author"; then
+                if [[ $view_author != "${heads_author[$pkg]}" ]]; then
+                    diff -u "$view_author" <(printf '%s\n' "${heads_author[$pkg]}") >"$tmp/$pkg.author" || true
+                fi
+
+            elif [[ -f $AUR_VIEW_DB/$pkg/author ]]; then
+                printf >&2 '%s: %s: failed to read author\n' "$argv0" "$pkg"
+                exit 1
+            else
+                # Always include author/email when unavailable (aurutils <=17)
+                diff -u /dev/null <(printf '%s\n' "${heads_author[$pkg]}") >"$tmp/$pkg.author" || true
+            fi
         fi
 
-    elif [[ -f $AUR_VIEW_DB/$pkg ]]; then
+    elif [[ -f $AUR_VIEW_DB/$pkg/head ]]; then
         printf >&2 '%s: %s: failed to read revision\n' "$argv0" "$pkg"
         exit 1
     fi
@@ -179,5 +197,6 @@ fi
 
 # Update gitsums (viewer exited successfully)
 for pkg in "${packages[@]}"; do
-    printf '%s\n' "${heads[$pkg]}" > "$AUR_VIEW_DB/$pkg"
+    printf '%s\n' "${heads[$pkg]}"        >"$AUR_VIEW_DB/$pkg/head"
+    printf '%s\n' "${heads_author[$pkg]}" >"$AUR_VIEW_DB/$pkg/author"
 done
```
It assumes a directory structure, created with e.g.
```
cd ~/.local/share/aurutils
for f in ./view/*; do g=$(basename "$f"); mkdir "view_author/$g"; cp "$f" view_author/"$g"/head; done
```
Run as follows:
```
export AUR_EXEC_PATH=<path to aurutils/lib checkout>
AUR_VIEW_DB=$HOME/.local/share/aurutils/view_author aur sync aurum --rebuild
```
Result:
![image](https://i.imgur.com/F2IEMCE.png)

**Comment by AladW** [comment]
As outlined above, this could be used to set up a simple "trust system":
```bash
#!/bin/bash
argv0=view-maintainer-change
trust_list=$XDG_CONFIG_HOME/aurutils/view/trusted

# Set up list of trusted author name/emails
declare -ad trust_list
while read -r auth; do
  trust_list[$auth]=1
done <"$trust_list"

# Upon maintainer change, verify if new maintainer is trusted.
# If not, inform the user and abort.
untrusted_pkgs=()
authors_diff=(*.author)
if [[ -f ${authors_diff[0]} ]]; then
  for ad in "${authors_diff[@]}"; do
    read -r author <"$ad"
    if [[ ${trust_list[$author]} != "1" ]]; then
      untrusted_pkgs+=("$ad")
    else
      printf >&2 '%s: trusted maintainer change: %s -> %s\n' "$author" "${trustlist[$author]}"
    fi
fi

if (( ${#untrusted_pkgs[@]} )); then
   printf >&2 '%s: untrusted maintainer changes\n'
   cat "${untrusted_pkgs[@]}"
   exit 2
else
   # viewing logic as desired
fi
```

**Comment by Strykar** [comment]
What I had in mind when I originally opened this was the AUR maintainer name change since that is static while their emails could change or be different than what is used for AUR git commits.

**Comment by AladW** [comment]
Right, but there is no way to map AUR (co-)maintainers to whoever pushed the commit. A series of co-maintainers might even push commits under the same common email, e.g. for some kind of CI/bot. Or the maintainer might have changed but no new commits were pushed. Even in ideal circumstances, there is the caching issue described above.

Another solution would be a commit API like Github, but that's something for aurweb to consider upstream.

**Comment by AladW** [comment]
https://gitlab.archlinux.org/archlinux/aurweb/-/issues/518

Until that is solved, there is no reliable solution on the aurutils side.
