### ISSUE TITLE
`sync`: `--ignore` should probably ignore packages provided via command-line

### ISSUE THREAD

**Issue by Earnestly** [aurutils/aurutils#952]
The `aurvcs.7` manual makes suggestion to provide packages via command-line, but at the same time it's not unreasonable for people to also ignore some of those if some are temporarily failing.

While it is possible to filter out the broken packages before providing them to the command-line itself this sort of behaviour is a little surprising.

If explicit listing on the command-line is the way to override an ignore from an ignore-file, perhaps a better approach is to use `[--no-ignore=pkg,...]...`

Essentially there's nothing functionally wrong with the current design but it is surprising.

**Comment by AladW** [comment]
The reason I went with this approach in 07ba7819d3f2b640d80f305789b3f217e611a36c is that
1. packages on the `aur-sync` command-line already take precedence for other purposes (`--provides`, `--no-ver-argv`)
2. it allows to quickly check an ignored package for updates (e.g. a fix for a regression) without modifying the (more permanent) `--ignore-file`

And (FWIW) `pacman` has the same behavior. I haven't thought on how it affects the workflow `aurvcs`, though.

**Comment by AladW** [comment]
Something like
```diff
diff --git a/man7/aurvcs.7 b/man7/aurvcs.7
index 577de4e..cb42396 100644
--- a/man7/aurvcs.7
+++ b/man7/aurvcs.7
@@ -30,6 +30,7 @@ Any option arguments are forwarded to
 .SS Program source
 .EX
     #!/bin/bash
+    set -e
     XDG_CACHE_HOME=${XDG_CACHE_HOME:\-$HOME/.cache}
     AURDEST=${AURDEST:\-$XDG_CACHE_HOME/aurutils/sync}
     AURVCS=${AURVCS:\-.*\-(cvs|svn|git|hg|bzr|darcs)$}
@@ -43,19 +44,24 @@ Any option arguments are forwarded to
         grep \-Fxf \- <(printf \(aq%s\en\(aq *) | xargs \-r aur srcver
     }
 
-    db_tmp=$(mktemp)
-    trap \(aqrm \-rf "$db_tmp"\(aq EXIT
+    # Scratch space for intermediary results.
+    tmp=$(mktemp \-d)
+    trap \(aqrm \-rf "$tmp"\(aq EXIT
 
     # Retrieve a list of the local repository contents. The repository
     # can be specified with the usual aur\-repo arguments.
-    aur repo \-\-list "$@" >"$db_tmp"
+    aur repo \-\-list "$@" >"$tmp"/db
+
+    # Pull any new AUR revisions (e.g. dependency updates) for VCS packages 
+    # and inspect them with aur-view(1).
+    cd "$AURDEST"
+    filter_vcs "$tmp"/db | tee "$tmp"/vcs | aur fetch -
+    aur view \-a "$tmp"/vcs
 
     # Find VCS packages that are outdated according to aur\-srcver.
     # This checks out the latest revision for existing source directories,
     # assuming the PKGBUILD has been viewed priorly.
-    if cd "$AURDEST"; then
-        aur vercmp \-p <(filter_vcs "$db_tmp" | get_latest_revision) <"$db_tmp"
-    fi
+    aur vercmp \-p <(get_latest_revision <"$tmp"/vcs) <"$tmp"/db
 .EE
 .
 .SS Notes
@@ -63,14 +69,14 @@ In the last line, the resulting package versions
 .RB ( "vcs_info" )
 are compared against the local repository
 .RB ( "db_info" ).
-If the package version is newer, it is printed to stdout. This may be
-combined with
-.BR aur\-sync (1)
+If the package version is newer, it is printed to stdout. The packages
+can then be built with
+.BR aur\-build (1)
 as follows:
 .PP
 .EX
-    $ mapfile \-t packages < <(aur vercmp\-devel | cut \-d" " \-f1)
-    $ aur sync "${packages[@]}" \-\-no\-ver\-argv
+    $ cd "$AURDEST"
+    $ aur build --arg-file <(aur vercmp\-devel | cut \-d" " \-f1)
 .EE
 .PP
 Version-control packages typically have
```

**Comment by AladW** [comment]
Going over `aurvcs.7` makes me wonder why `aur-srcver` makes any attempts to limit effects of sourcing PKGBUILDs, when it runs `makepkg` anyway...

**Comment by AladW** [comment]
Another observation is that `aur-srcver` can't take input from `stdin`. I guess this was an oversight when migrating scripts to use `-`.
